---
title: "Seed Theory - Diversity"
author: "Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW
Summary statistics associated with cartoon figure 2

## 1) SETUP

### A. Retrieve and Set Your Working Directory

```{r, results = 'hide'}
rm(list = ls())
getwd()
setwd("~/GitHub/seedtheory")
library("vegan")
```

### B. Load data

```{r}
seed <- read.table("seed.diversity.txt", sep = "\t", header = TRUE)
seed.dorm <- seed$abund.dorm
seed.act <- seed$abund.act
```

## 2) DIVERSITY CALCULATIONS

```{r}
# Total abundance (N)
seed.dorm.N <- sum(seed.dorm)
seed.act.N <- sum(seed.act)

# Observed richness
S.obs <- function(x = ""){
  rowSums(x > 0) * 1
}

S.dorm <- S.obs(t(seed.dorm))
S.act <- S.obs(t(seed.act))

# Beta diversity similarity

seed.dist <- vegdist(t(seed[2:3]), "bray")








# Visualize rank abundance curve
RAC <- function(x = ""){
  x = as.vector(x)
  x.ab = x[x > 0]
  x.ab.ranked = x.ab[order(x.ab, decreasing = TRUE)]
  return(x.ab.ranked)
  }

plot.new()
site1 <- t(jb$count)

rac <- RAC(x = site1)
ranks <- as.vector(seq(1, length(rac)))
opar <- par(no.readonly = TRUE)                       # Saves default plot parameters
par(mar = c(5.1, 5.1, 4.1, 2.1))                      # New settings for par
plot(ranks, log(rac), type = 'p', axes = F,           # Plots w/o axes
     xlab = "Rank in abundance", ylab = "Abundance",
     las = 1, cex.lab = 1.4, cex.axis = 1.25)

box()                                                 # Manually adds border
axis(side = 1, labels = T, cex.axis = 1.25)           # Manually adds X-axis
axis(side = 2, las = 1, cex.axis = 1.25,              # Manually adds Log-Scaled Y-axis
     labels = c(1, 2, 5, 10, 20, 50), at = log(c(1, 2, 5, 10, 20, 50)))

par <- opar                                           # Resets plotting parameters

# Smith and Wilson's Evenness Index (Evar)
Evar <- function(x){
  x <- as.vector(x[x > 0])
  1 - (2/pi)*atan(var(log(x)))
  }

Evar(t(jb[,5]))

# Shannon's Diversity (H')
ShanH <- function(x = ""){
  H = 0
  for (n_i in x){
    if(n_i > 0) {
      p = n_i / sum(x)
      H = H - p*log(p) 
    }
  }
  return(H)
}

ShanH(t(jb$count))
```


